services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TalanHdf\SemanticSuggestion\:
    resource: '../Classes/*'

  TalanHdf\SemanticSuggestion\Service\StopWordsService:
    public: true

  TalanHdf\SemanticSuggestion\Service\PageAnalysisService:
    arguments:
      $context: '@TYPO3\CMS\Core\Context\Context'
      $configurationManager: '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
      $siteFinder: '@TYPO3\CMS\Core\Site\SiteFinder'
      $cacheManager: '@TYPO3\CMS\Core\Cache\CacheManager'
      $stopWordsService: '@TalanHdf\SemanticSuggestion\Service\StopWordsService'
      $connectionPool: '@TYPO3\CMS\Core\Database\ConnectionPool'
    public: true

  TalanHdf\SemanticSuggestion\Service\LanguageService:
    public: true
    arguments:
      $siteFinder: '@TYPO3\CMS\Core\Site\SiteFinder'
      $context: '@TYPO3\CMS\Core\Context\Context'
      $logManager: '@TYPO3\CMS\Core\Log\LogManager'
    tags:
      - name: 'backend.controller'

  TalanHdf\SemanticSuggestion\Service\UtilityService:
    public: true
    arguments:
      $pageAnalysisService: '@TalanHdf\SemanticSuggestion\Service\PageAnalysisService'
      $logManager: '@TYPO3\CMS\Core\Log\LogManager'

  TalanHdf\SemanticSuggestion\Service\SuggestionService:
    public: true
    arguments:
      $pageAnalysisService: '@TalanHdf\SemanticSuggestion\Service\PageAnalysisService'
      $fileRepository: '@TYPO3\CMS\Core\Resource\FileRepository'
      $pageRepository: '@TYPO3\CMS\Core\Domain\Repository\PageRepository'
      $utility: '@TalanHdf\SemanticSuggestion\Service\UtilityService'

  TYPO3\CMS\Core\Log\LogManager:
    public: true

  TalanHdf\SemanticSuggestion\Controller\SuggestionsController:
    public: true
    arguments:
      $pageAnalysisService: '@TalanHdf\SemanticSuggestion\Service\PageAnalysisService'
      $suggestionService: '@TalanHdf\SemanticSuggestion\Service\SuggestionService'
      $utility: '@TalanHdf\SemanticSuggestion\Service\UtilityService'

  TalanHdf\SemanticSuggestion\Controller\SemanticBackendController:
    public: true
    arguments:
      $moduleTemplateFactory: '@TYPO3\CMS\Backend\Template\ModuleTemplateFactory'
      $pageAnalysisService: '@TalanHdf\SemanticSuggestion\Service\PageAnalysisService'
      $logManager: '@TYPO3\CMS\Core\Log\LogManager'
      $languageService: '@TalanHdf\SemanticSuggestion\Service\LanguageService'
      $flashMessageService: '@TYPO3\CMS\Core\Messaging\FlashMessageService'  # Ajouté ici
    tags:
      - name: 'controller.backend_controller'
