services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TalanHdf\SemanticSuggestion\:
    resource: '../Classes/*'

  TalanHdf\SemanticSuggestion\Service\StopWordsService:
    public: true

  TalanHdf\SemanticSuggestion\Service\PageAnalysisService:
    arguments:
      $context: '@TYPO3\CMS\Core\Context\Context'
      $configurationManager: '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
      $siteFinder: '@TYPO3\CMS\Core\Site\SiteFinder'
      $cacheManager: '@TYPO3\CMS\Core\Cache\CacheManager'
      $stopWordsService: '@TalanHdf\SemanticSuggestion\Service\StopWordsService'
      $connectionPool: '@TYPO3\CMS\Core\Database\ConnectionPool'
    public: true

  TalanHdf\SemanticSuggestion\Service\LanguageService:
    public: true
    arguments:
      $siteFinder: '@TYPO3\CMS\Core\Site\SiteFinder'
      $context: '@TYPO3\CMS\Core\Context\Context'
      $logManager: '@TYPO3\CMS\Core\Log\LogManager'
    tags:
      - name: 'backend.controller'

  TYPO3\CMS\Core\Log\LogManager:
    public: true

  TalanHdf\SemanticSuggestion\Controller\SuggestionsController:
    public: true
    arguments:
      $pageAnalysisService: '@TalanHdf\SemanticSuggestion\Service\PageAnalysisService'

  TalanHdf\SemanticSuggestion\Controller\SemanticBackendController:
    public: true
    autowire: true
    autoconfigure: true
    tags: ['controller.backend_controller']
    arguments:
      $logManager: '@TYPO3\CMS\Core\Log\LogManager'